<?php

namespace PolcodeProductBundle\Repository;

/**
 * PolcodeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolcodeProductRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Find product by translated slug field
     * @param type $slug
     * @return type
     */
    public function findOneBySlug($slug)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p, t')
            ->join('p.translations', 't')
            ->where('t.slug = :slug')
            ->setParameter('slug', $slug);

        return $qb->getQuery()->getSingleResult();
    }
    
}
