<?php

namespace PolcodeProductBundle\Repository;

/**
 * PolcodeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolcodeCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
