<?php

namespace PolcodeProductBundle\Repository;

/**
 * PolcodeProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolcodeProductRepository extends \Doctrine\ORM\EntityRepository
{
}
