services:
    polcode_product.admin.polcode_category:
        class: PolcodeProductBundle\Admin\PolcodeCategoryAdmin
        arguments: [~, PolcodeProductBundle\Entity\PolcodeCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Polcode, label: PolcodeCategory }

    polcode_product.admin.polcode_product:
        class: PolcodeProductBundle\Admin\PolcodeProductAdmin
        arguments: [~, PolcodeProductBundle\Entity\PolcodeProduct, PolcodeProductBundle:ProductCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Polcode, label: PolcodeProduct }
        calls:
            - [ setTemplate, [list__action_delete, PolcodeProductBundle:PolcodeProduct:list.html.twig]]
            
    app.menu_builder:
        class: PolcodeProductBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@doctrine.orm.entity_manager", '@security.authorization_checker']
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
